### ISSUE TITLE
Fails during npm install

### ISSUE THREAD

**Issue by kenOfYugen** [charto/nbind-examples#1]
Hello @jjrv, and thanks for nbind!

```
$ npm install

> nbind-examples@0.2.0 install /home/ken/Desktop/nbind-examples
> autogypi && node-gyp configure build

make: Entering directory '/home/ken/Desktop/nbind-examples/build'
  CXX(target) Release/obj.target/nbind/6-functions.o
In file included from ../node_modules/nbind/include/nbind/BindDefiner.h:20:0,
                 from ../node_modules/nbind/include/nbind/nbind.h:8,
                 from ../6-functions.cc:7:
../node_modules/nbind/include/nbind/v8/Overloader.h: In static member function ‘static void nbind::Overloader::callNew(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../node_modules/nbind/include/nbind/v8/Overloader.h:105:68: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   args.GetReturnValue().Set(constructor->NewInstance(argc, &argv[0]));
                                                                    ^
In file included from /home/ken/.node-gyp/6.7.0/include/node/v8.h:25:0,
                 from ../node_modules/nbind/include/nbind/v8/BindWrapper.h:14,
                 from ../node_modules/nbind/include/nbind/api.h:62,
                 from ../node_modules/nbind/include/nbind/BindDefiner.h:11,
                 from ../node_modules/nbind/include/nbind/nbind.h:8,
                 from ../6-functions.cc:7:
/home/ken/.node-gyp/6.7.0/include/node/v8.h:3270:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/ken/.node-gyp/6.7.0/include/node/v8config.h:333:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../6-functions.cc: At global scope:
../6-functions.cc:9:14: error: ISO C++ forbids declaration of ‘NBIND_GLOBAL’ with no type [-fpermissive]
 NBIND_GLOBAL() {
              ^
../6-functions.cc: In function ‘int NBIND_GLOBAL()’:
../6-functions.cc:10:20: error: ‘function’ was not declared in this scope
   function(sayHello);
                    ^
../6-functions.cc:10:20: note: suggested alternative:
In file included from /usr/include/c++/6.2.1/memory:79:0,
                 from ../node_modules/nbind/include/nbind/v8/BindWrapper.h:6,
                 from ../node_modules/nbind/include/nbind/api.h:62,
                 from ../node_modules/nbind/include/nbind/BindDefiner.h:11,
                 from ../node_modules/nbind/include/nbind/nbind.h:8,
                 from ../6-functions.cc:7:
/usr/include/c++/6.2.1/functional:1535:11: note:   ‘std::function’
     class function;
           ^~~~~~~~
../6-functions.cc:11:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
make: *** [nbind.target.mk:108: Release/obj.target/nbind/6-functions.o] Error 1
make: Leaving directory '/home/ken/Desktop/nbind-examples/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.7.6-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/ken/Desktop/nbind-examples
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Linux 4.7.6-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! nbind-examples@0.2.0 install: `autogypi && node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nbind-examples@0.2.0 install script 'autogypi && node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nbind-examples package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     autogypi && node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nbind-examples
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nbind-examples
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ken/Desktop/nbind-examples/npm-debug.log
```

---

```
$ npm test 

> nbind-examples@0.2.0 test /home/ken/Desktop/nbind-examples
> node 0-hello.js

/home/ken/Desktop/nbind-examples/node_modules/nbind/dist/nbind.js:30
        throw (err);
        ^

Error: Could not locate the bindings file. Tried:
/home/ken/Desktop/nbind-examples/nbind.node
/home/ken/Desktop/nbind-examples/build/nbind.node
/home/ken/Desktop/nbind-examples/build/Debug/nbind.node
/home/ken/Desktop/nbind-examples/build/Release/nbind.node
/home/ken/Desktop/nbind-examples/out/Debug/nbind.node
/home/ken/Desktop/nbind-examples/Debug/nbind.node
/home/ken/Desktop/nbind-examples/out/Release/nbind.node
/home/ken/Desktop/nbind-examples/Release/nbind.node
/home/ken/Desktop/nbind-examples/build/default/nbind.node
/home/ken/Desktop/nbind-examples/compiled/6.7.0/linux/ia32/nbind.node
/home/ken/Desktop/nbind-examples/nbind.js
/home/ken/Desktop/nbind-examples/build/nbind.js
/home/ken/Desktop/nbind-examples/build/Debug/nbind.js
/home/ken/Desktop/nbind-examples/build/Release/nbind.js
/home/ken/Desktop/nbind-examples/out/Debug/nbind.js
/home/ken/Desktop/nbind-examples/Debug/nbind.js
/home/ken/Desktop/nbind-examples/out/Release/nbind.js
/home/ken/Desktop/nbind-examples/Release/nbind.js
/home/ken/Desktop/nbind-examples/build/default/nbind.js
/home/ken/Desktop/nbind-examples/compiled/6.7.0/linux/ia32/nbind.js
    at findCompiledModule (/home/ken/Desktop/nbind-examples/node_modules/nbind/dist/nbind.js:98:15)
    at find (/home/ken/Desktop/nbind-examples/node_modules/nbind/dist/nbind.js:108:13)
    at Object.init (/home/ken/Desktop/nbind-examples/node_modules/nbind/dist/nbind.js:119:5)
    at Object.<anonymous> (/home/ken/Desktop/nbind-examples/0-hello.js:2:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
npm ERR! Test failed.  See above for more details.
```

`node@6.7.0` `npm@3.10.8` `nbind@0.2.1` `node-gyp@3.4.0` `auto-gypi@0.2.2`
`$ uname -a` `Linux nbook 4.7.6-1-ARCH #1 SMP PREEMPT Fri Sep 30 19:46:40 CEST 2016 i686 GNU/Linux`
I got the `nbind` version from the `node_modules/nbind/package.json`. 

When I force nbind@0.3.4, I get it to build with warnings.

From Mac OS X 10.11.6

```
Kens-MacBook-Pro:nbind-examples ken$ npm install
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color

> nbind-examples@0.2.0 install /Users/ken/Desktop/nbind-examples
> autogypi && node-gyp configure build

  CXX(target) Release/obj.target/nbind/0-hello.o
  CXX(target) Release/obj.target/nbind/1-headers.o
  CXX(target) Release/obj.target/nbind/2-classes.o
  CXX(target) Release/obj.target/nbind/3-methods.o
  CXX(target) Release/obj.target/nbind/4-getset.o
  CXX(target) Release/obj.target/nbind/5-objects.o
  CXX(target) Release/obj.target/nbind/6-functions.o
../6-functions.cc:9:1: error: C++ requires a type specifier for all declarations
NBIND_GLOBAL() {
^
../6-functions.cc:10:3: error: use of undeclared identifier 'function'
  function(sayHello);
  ^
2 errors generated.
make: *** [Release/obj.target/nbind/6-functions.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/ken/Desktop/nbind-examples
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! nbind-examples@0.2.0 install: `autogypi && node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nbind-examples@0.2.0 install script 'autogypi && node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nbind-examples package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     autogypi && node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nbind-examples
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nbind-examples
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ken/Desktop/nbind-examples/npm-debug.log
```

When I force nbind@0.3.4, I still get the errors.
Is the functionality in example 6 not implemented yet in nbind? Or am I doing something wrong here?

**Comment by jjrv** [comment]
Sorry, the example 6 requires a later version of nbind than referenced in `package.json`. Updating to 0.3.4 should work though, I just tried with OS X. I've now updated the repository, try cloning it again or `git pull` and remove the `build` and `node_modules` directories. Then `npm install` should definitely work.

Thanks for reporting!

**Comment by kenOfYugen** [comment]
Thank you, all examples build and run perfectly in both linux and mac.
